<?php

/**
 * @file
 * Main module file.
 */

global $conf;

// Auto-rebuild the theme registry.
if (variable_get('registryonsteroids_rebuild_registry', FALSE) && !defined('MAINTENANCE_MODE')) {
  // Rebuild .info data.
  system_rebuild_theme_data();
  // Rebuild theme registry.
  drupal_theme_rebuild();
}

$conf['theme_debug'] = variable_get('registryonsteroids_theme_debug', FALSE);

/**
 * Implements hook_menu().
 *
 * @return array[]
 */
function registryonsteroids_menu() {
  return array(
    'admin/config/development/registryonsteroids' => array(
      'title' => 'Registry On Steroïds',
      'description' => 'Registry On Steroïds configuration',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('_registryonsteroids_admin_settings'),
      'access arguments' => array(
        'administer site',
      ),
      'file' => 'registryonsteroids.admin.inc',
    ),
  );
}

/**
 * Implements hook_module_implements_alter().
 *
 * @param mixed[] $implementations
 *   Format: $[$module] = $group
 * @param string $hook
 */
function registryonsteroids_module_implements_alter(array &$implementations, $hook) {
  if ('theme_registry_alter' === $hook) {
    /* @see _registryonsteroids_first_theme_registry_alter() */
    $implementations = array('_registryonsteroids_first' => FALSE) + $implementations;

    /* @see _registryonsteroids_last_theme_registry_alter() */
    $implementations['_registryonsteroids_last'] = FALSE;
  }
}

/**
 * Callback for hook_theme_registry_alter().
 *
 * Registered to run before all other implemntations.
 *
 * @param array[] $registry
 *   Format: $[$theme_hook] = $info
 */
function _registryonsteroids_first_theme_registry_alter(array &$registry) {
  // Figure out which theme this applies to.
  if (PHP_VERSION_ID >= 50400) {
    $trace = debug_backtrace(0, 3);
  }
  else {
    // Second parameter not supported in PHP < 5.4.0. It would cause a
    // "Warning: debug_backtrace() expects at most 1 parameter, 2 given".
    $trace = debug_backtrace(0);
  }
  if (!isset($trace[2]['function'], $trace[2]['args'][0])
    || '_theme_build_registry' !== $trace[2]['function']) {
    watchdog(
      'registryonsteroids',
      'hook_theme_registry_alter() was called from an unexpected place. We cannot determine which theme this registry belongs to. registryonsteroids functionality might not work.',
      [],
      WATCHDOG_WARNING
    );

    return;
  }

  /* @see _theme_build_registry() */
  list($theme, $base_themes) = $trace[2]['args'];

  // Include all files registered as 'include' for theme hooks, so that
  // get_defined_functions() finds all preprocess functions.
  $include_files_map = array();
  foreach ($registry as $info) {
    if (isset($info['includes'])) {
      foreach ($info['includes'] as $include_file) {
        $include_files_map[$include_file] = $include_file;
      }
    }
  }

  foreach ($include_files_map as $include_file) {
    include_once DRUPAL_ROOT . '/' . $include_file;
  }

  $user_functions = get_defined_functions()['user'];

  /**
   * @var string[][] $prefixes_by_type
   *   Format: $[$prefix_type][$prefix] = $prefix
   */
  $prefixes_by_type = _registryonsteroids_theme_make_prefixes($base_themes, $theme);

  /**
   * @var string[] $prefixes
   *   Format: $[$prefix] = $prefix
   */
  $prefixes = array_merge(...array_values($prefixes_by_type));

  // Apply Registry On Steroids sauce.
  _registryonsteroids_first_theme_registry_do_alter($registry, $base_themes, $theme, $user_functions, $prefixes);
}

/**
 * Alter the registry - first part of the workflow.
 *
 * @param array[] $registry
 * @param object[] $base_themes
 * @param object $theme
 * @param string[] $user_functions
 * @param string[] $prefixes
 */
function _registryonsteroids_first_theme_registry_do_alter(array &$registry, array $base_themes, $theme, array $user_functions, array $prefixes) {
  ksort($registry);

  $functions_by_hook_and_phase_and_weight = _registryonsteroids_group_functions_by_hook_and_phase_and_weight($user_functions, $prefixes);
  $functions_by_hook_and_phase_and_weight += array('*' => array());

  $declared_hooks = array_keys($registry);
  $declared_hooks = array_combine($declared_hooks, $declared_hooks);

  $declared_base_hooks = array();
  $declared_root_hooks = array();
  foreach ($registry as $hook => $info) {
    $declared_root_hooks[$hook] = $hook;
    if (isset($info['base hook']) && $hook !== $info['base hook']) {
      $declared_root_hooks[$hook] = $hook;
      $declared_base_hooks[$hook] = $info['base hook'];
    }
  }

  $discovered_hooks = array_keys($functions_by_hook_and_phase_and_weight);
  $discovered_hooks = array_combine($discovered_hooks, $discovered_hooks);
  $discovered_undeclared_hooks = array_diff_key($discovered_hooks, $declared_hooks);
  $discovered_undeclared_variants = preg_grep('@__@', $discovered_undeclared_hooks);

  $functions_r_by_hook_and_phase = array();
  foreach ($functions_by_hook_and_phase_and_weight as $hook => $functions_by_phase_and_weight) {
    foreach ($functions_by_phase_and_weight as $phase => $functions_by_weight) {
      $functions_r_by_hook_and_phase[$hook][$phase] = array_combine($functions_by_weight, $functions_by_weight);
    }
  }

  $sortme = array();
  foreach (array($declared_hooks, $discovered_undeclared_hooks) as $hooks) {
    foreach ($hooks as $hook) {
      $sortme[$hook . '__'] = $hook;
      $sortme[$hook . '__|'] = FALSE;
    }
  }

  ksort($sortme);

  $trail = array();
  $base_hooks = $declared_base_hooks;
  $cascades = array();
  $parent = '*';
  $base_hook = '*';
  $cascade = array();
  foreach ($sortme as $hook_or_false) {
    // Invariants:
    // - $cascade is the cascade of $parent
    // - $base_hook is the base hook of $parent
    //   (with $base_hook === $parent, if it is a "root" hook)
    // - $cascades[$trail[$i]] is known for each $i in $trail.
    // - $base_hooks[$trail[$i]] is known for each $i in $trail.
    if (FALSE === $hook_or_false) {
      $parent = array_pop($trail);
      $cascade = $cascades[$parent];
      $base_hook = $base_hooks[$parent];
      continue;
    }

    $trail[] = $parent;
    $parent = $hook_or_false;
    if (isset($declared_root_hooks[$parent])) {
      $cascade = array($parent);
      $base_hook = $parent;
    }
    elseif (!isset($base_hooks[$parent])) {
      $cascade[] = $parent;
      // $base_hook stays the same.
    }
    elseif ($base_hook === $base_hooks[$parent]) {
      $cascade[] = $parent;
      // $base_hook stays the same.
    }
    else {
      $base_hook = $base_hooks[$parent];
      $cascade = array($base_hook, $parent);
    }
    $cascades[$parent] = $cascade;
    $base_hooks[$parent] = $base_hook;
  }

  $registry_entries_to_add = array();
  foreach ($discovered_undeclared_variants as $undeclared_variant) {
    $base_hook = $undeclared_variant;
    while (!isset($registry[$base_hook])) {
      if (FALSE === $pos = strrpos($base_hook, '__')) {
        break 2;
      }
      $base_hook = drupal_substr($base_hook, 0, $pos);
    }
    $base_hook_info = $registry[$base_hook];
    while (!empty($base_hook_info['base hook'])) {
      $base_hook = $base_hook_info['base hook'];
      if (!isset($registry[$base_hook])) {
        break 2;
      }
      $base_hook_info = $registry[$base_hook];
    }
    $registry_entry = $base_hook_info;
    $registry_entry['base hook'] = $base_hook;
    $registry_entries_to_add[$undeclared_variant] = $registry_entry;
  }

  $registry += $registry_entries_to_add;

  $functionss_accum_by_basehook_and_phasekey_and_weight = array();
  foreach ($functions_by_hook_and_phase_and_weight['*'] as $phase => $functions_by_weight) {
    $phase_key = $phase . ' functions';
    foreach ($declared_root_hooks as $hook) {
      if (!empty($registry[$hook]['template'])) {
        foreach ($functions_by_weight as $weight => $function) {
          $functionss_accum_by_basehook_and_phasekey_and_weight[$hook][$phase_key][$weight][] = $function;
        }
        unset($weight, $function);
      }
    }
    unset($phase_key, $hook);
  }
  unset($phase, $functions_by_weight);

  foreach ($functions_by_hook_and_phase_and_weight as $hook => $functions_by_phase_and_weight) {
    if ('*' === $hook) {
      continue;
    }

    $base_hook = $base_hooks[$hook];
    $cascade = $cascades[$hook];
    array_pop($cascade);
    foreach ($functions_by_phase_and_weight as $phase => $functions_by_weight) {
      $phase_key = $phase . ' functions';
      foreach ($functions_by_weight as $weight => $function) {
        $functionss_accum_by_basehook_and_phasekey_and_weight[$base_hook][$phase_key][$weight][] = $function;
      }
    }
  }

  foreach (_registryonsteroids_theme_processors_phases() as $phase_key => $phase) {
    $phase_template_root_functions_r = isset($functions_r_by_hook_and_phase['*'][$phase])
      ? $functions_r_by_hook_and_phase['*'][$phase]
      : array();
    $trail = array();
    $parent = '*';
    $base_hook = '*';
    $removables_r_by_hook = array();
    $removables_r = array();

    foreach ($sortme as $hook_or_false) {
      if (FALSE === $hook_or_false) {
        $parent = array_pop($trail);
        $removables_r = $removables_r_by_hook[$parent];
        continue;
      }

      $trail[] = $parent;
      $parent = $hook_or_false;

      if (isset($declared_root_hooks[$parent])) {
        $removables_r = array();
        if (isset($functionss_accum_by_basehook_and_phasekey_and_weight[$parent][$phase_key])) {
          $removables_r = array_merge(...$functionss_accum_by_basehook_and_phasekey_and_weight[$parent][$phase_key]);
          $removables_r = array_combine($removables_r, $removables_r);
          if (isset($registry[$parent]['template'])) {
            if (array() !== $phase_template_root_functions_r) {
              $removables_r = array_diff($removables_r, $phase_template_root_functions_r);
            }
          }
        }
      }
      elseif (!isset($base_hooks[$parent]) || $base_hook === $base_hooks[$parent]) {
        // $removables_r stays the same.
        // $base_hook stays the same.
      }
      else {
        $base_hook = $base_hooks[$parent];
        $removables_r = $removables_r_by_hook[$base_hook];
      }

      if (isset($functions_r_by_hook_and_phase[$parent][$phase])) {
        $removables_r = array_diff_key(
          $removables_r,
          $functions_r_by_hook_and_phase[$parent][$phase]);
      }

      $removables_r_by_hook[$parent] = $removables_r;
      $registry[$parent]['registryonsteroids unset'][$phase_key] = $removables_r;
    }
  }

  foreach ($functionss_accum_by_basehook_and_phasekey_and_weight as $hook => $functionss_by_phasekey_and_weight) {
    if ('*' === $hook) {
      continue;
    }

    foreach ($functionss_by_phasekey_and_weight as $phase_key => $functionss_by_weight) {
      ksort($functionss_by_weight);
      $registry[$hook][$phase_key] = array_merge(...$functionss_by_weight);
    }
  }

  ksort($registry);
}

/**
 * Callback for hook_theme_registry_alter()
 *
 * Registered to run after all other implemntations.
 *
 * @param array[] $registry
 *   Format: $[$theme_hook] = $info
 */
function _registryonsteroids_last_theme_registry_alter(array &$registry) {
  foreach ($registry as &$info) {
    if (isset($info['base hook'])) {
      $base_hook = $info['base hook'];
      if (!isset($registry[$base_hook])) {
        // @todo Log this.
        continue;
      }
      $base_hook_info = $registry[$base_hook];
      foreach (['preprocess functions', 'process functions'] as $phase_key) {
        $info[$phase_key] = isset($base_hook_info[$phase_key])
          ? $base_hook_info[$phase_key]
          : [];
      }

      unset($info['base hook']);
    }
  }

  foreach ($registry as &$info) {
    if (!isset($info['registryonsteroids unset'])) {
      continue;
    }

    foreach ($info['registryonsteroids unset'] as $phase_key => $functions_to_remove) {
      if (empty($info[$phase_key])) {
        continue;
      }
      $info[$phase_key] = array_values(
        array_diff(
          $info[$phase_key],
          $functions_to_remove));
    }

    unset($info['registryonsteroids unset']);
  }

  unset($registry['*']);
}

/**
 * Get processors name and machine name.
 *
 * Processor functions work in two distinct phases with the process
 * functions always being executed after the preprocess functions.
 *
 * @return array
 *   The processors names and machine names.
 */
function _registryonsteroids_theme_processors_phases() {
  return array(
    'preprocess functions' => 'preprocess',
    'process functions'    => 'process',
  );
}

/**
 * Compile a list of prefixes.
 *
 * The order of this is very important.
 *
 * @param object[] $base_themes
 *   The array of base themes.
 * @param object $theme
 *   The current theme.
 *
 * @see https://api.drupal.org/api/drupal/includes!theme.inc/function/theme/7.x
 *
 * @return string[][]
 *   The prefixes.
 *   Format: $[$prefix_type][$prefix] = $prefix
 */
function _registryonsteroids_theme_make_prefixes(array $base_themes, $theme) {
  return array(
    'template' => array(
      'template' => 'template',
    ),
    'module' => module_list(),
    'theme_engine' => array(
      $theme->engine => $theme->engine,
    ),
    'base_theme' => array_combine(
      array_keys($base_themes),
      array_keys($base_themes)
    ),
    'theme' => array(
      $theme->name => $theme->name,
    ),
  );
}

/**
 * Group functions by hook and phase, with inheritance.
 *
 * @param string[] $user_functions
 * @param string[] $prefixes
 *   A whitelist of prefixes (module names, themes, etc).
 *
 * @return string[][][]
 *   Format: $[$hook][$phase][] = $function
 *   E.g. $['block']['preprocess'][] = 'system_preprocess_block'.
 */
function _registryonsteroids_group_functions_by_hook_and_phase_with_inheritance(array $user_functions, array $prefixes) {
  $functions_by_hook_and_phase_and_weight = _registryonsteroids_group_functions_by_hook_and_phase_and_weight($user_functions, $prefixes);

  $functions_by_hook_and_phase_and_weight_extended = $functions_by_hook_and_phase_and_weight;
  foreach ($functions_by_hook_and_phase_and_weight as $hook => $functions_by_phase) {
    $functions_by_hook_and_phase_and_weight_extended[$hook . '__'] = TRUE;
    $functions_by_hook_and_phase_and_weight_extended[$hook . '__|'] = FALSE;
  }

  ksort($functions_by_hook_and_phase_and_weight_extended);

  $keys = array_keys($functions_by_hook_and_phase_and_weight_extended);
  $keymap = array_flip($keys);
  $skipmap = array();
  foreach ($keys as $i => $key) {
    $entry = $functions_by_hook_and_phase_and_weight_extended[$key];
    if (TRUE === $entry || FALSE === $entry) {
      $skipmap[$i] = TRUE;
    }
  }

  $functionss_by_hook_and_phase_and_weight_with_inheritance = array();
  foreach ($keys as $i => $key) {
    if (TRUE !== $functions_by_hook_and_phase_and_weight_extended[$key]) {
      continue;
    }
    $end_key = $key . '|';
    $i_end = $keymap[$end_key];
    $parent_hook = $keys[$i - 1];
    $parent_hook_functions_by_phase_and_weight = $functions_by_hook_and_phase_and_weight_extended[$parent_hook];

    for ($j = $i - 1; $j < $i_end; ++$j) {
      if (isset($skipmap[$j])) {
        continue;
      }
      $hook_j = $keys[$j];
      foreach ($parent_hook_functions_by_phase_and_weight as $phase => $functions_by_weight) {
        foreach ($functions_by_weight as $weight => $function) {
          $functionss_by_hook_and_phase_and_weight_with_inheritance[$hook_j][$phase][$weight][] = $function;
        }
      }
    }
  }

  $functionss_by_hook_and_phase_with_inheritance = array();
  foreach ($functionss_by_hook_and_phase_and_weight_with_inheritance as $hook => $functionss_by_phase_and_weight) {
    foreach ($functionss_by_phase_and_weight as $phase => $functionss_by_weight) {
      ksort($functionss_by_weight);
      $functionss_by_hook_and_phase_with_inheritance[$hook][$phase] = array_merge(...$functionss_by_weight);
    }
  }

  return $functionss_by_hook_and_phase_with_inheritance;
}

/**
 * Group functions by hook, phase and weight.
 *
 * @param string[] $user_functions
 * @param string[] $prefixes
 *   A whitelist of prefixes (module names, themes, etc).
 *
 * @return string[][][]
 *   Format: $[$hook][$phase][$weight] = $function
 *   E.g. $['block']['preprocess'][51] = 'system_preprocess_block'.
 */
function _registryonsteroids_group_functions_by_hook_and_phase_and_weight(array $user_functions, array $prefixes) {
  $functions_by_prefix_and_phase_filtered = _registryonsteroids_group_functions_by_prefix_and_phase_filtered(
    $user_functions,
    $prefixes);

  $functions_by_hook_and_phase_and_weight = array();
  $weight = 0;
  foreach ($functions_by_prefix_and_phase_filtered as $functions_by_phase) {
    foreach ($functions_by_phase as $phase => $functions_by_hook) {
      foreach ($functions_by_hook as $hook => $function) {
        $functions_by_hook_and_phase_and_weight[$hook][$phase][$weight] = $function;
      }
    }
    ++$weight;
  }

  ksort($functions_by_hook_and_phase_and_weight);

  return $functions_by_hook_and_phase_and_weight;
}

/**
 * Group functions by prefix and phase, but filtered.
 *
 * @param string[] $user_functions
 * @param string[] $prefixes
 *   A whitelist of prefixes (module names, themes, etc).
 *
 * @return string[][][]
 *   Format: $[$prefix][$phase][$themehook] = $function
 *   E.g. $['system']['preprocess']['block'] = 'system_preprocess_block'.
 */
function _registryonsteroids_group_functions_by_prefix_and_phase_filtered(array $user_functions, array $prefixes) {
  $functions_by_prefix_and_phase = _registryonsteroids_group_functions_by_prefix_and_phase(
    $user_functions);

  // Only keep functions with known prefix.
  $functions_by_prefix_and_phase_filtered = array();
  foreach ($prefixes as $prefix) {
    if (!isset($functions_by_prefix_and_phase[$prefix])) {
      continue;
    }
    $functions_by_prefix_and_phase_filtered[$prefix] = $functions_by_prefix_and_phase[$prefix];
  }

  return $functions_by_prefix_and_phase_filtered;
}

/**
 * Group functions by prefix and phase.
 *
 * @param string[] $user_functions
 *
 * @return string[][][]
 *   Format: $[$prefix][$phase][$themehook] = $function
 *   E.g. $['system']['preprocess']['block'] = 'system_preprocess_block'.
 */
function _registryonsteroids_group_functions_by_prefix_and_phase(array $user_functions) {
  $candidate_functions = preg_grep('/process/', $user_functions);

  $functions_by_prefix_and_phase = [];
  foreach (array('preprocess', 'process') as $phase) {
    $needle = '_' . $phase . '_';

    $phase_functions = preg_grep('/_' . $phase . '_/', $candidate_functions);
    foreach ($phase_functions as $function) {
      $fragments = explode($needle, $function);
      if (!isset($fragments[1])) {
        // This should be unreachable code with the preg_grep() above.
        continue;
      }

      if (!isset($fragments[2])) {
        // This is the normal case with only one occurence of $needle.
        list($prefix, $hook) = $fragments;
        $functions_by_prefix_and_phase[$prefix][$phase][$hook] = $function;
        continue;
      }

      // This is a rare case with more than one occurence of $needle.
      // This doesn't have to be very fast, because it is rare.
      $prefix = array_shift($fragments);
      while (array() !== $fragments) {
        $hook = implode($needle, $fragments);
        $functions_by_prefix_and_phase[$prefix][$phase][$hook] = $function;
        $prefix .= $needle . array_shift($fragments);
      }
    }

    $phase_functions = preg_grep('/_' . $phase . '$/', $candidate_functions);
    $substr_length = -drupal_strlen($phase) - 1;
    foreach ($phase_functions as $function) {
      $prefix = drupal_substr($function, 0, $substr_length);
      $functions_by_prefix_and_phase[$prefix][$phase]['*'] = $function;
    }
  }

  return $functions_by_prefix_and_phase;
}
