<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_theme().
 */
function ros_test_theme() {
  return array(
    'ros0' => array(
      'variables' => array(
        'text' => __FUNCTION__ . ',',
      ),
      'template' => 'ros0',
    ),
    'ros1' => array(
      'variables' => array(
        'text' => __FUNCTION__ . ',',
      ),
      'template' => 'ros1',
    ),
    'ros2' => array(
      'variables' => array(
        'text' => __FUNCTION__ . ',',
      ),
      'template' => 'ros2',
    ),
  );
}

/**
 * Implements hook_preprocess_hook().
 */
function ros_test_preprocess_ros0(&$variables, $hook) {
  $variables['text'] .= __FUNCTION__ . ',';
}

/**
 * Implements hook_preprocess_hook().
 */
function ros_test_preprocess_ros1(&$variables, $hook) {
  $variables['text'] .= __FUNCTION__ . ',';
}

/**
 * Implements hook_preprocess_hook().
 */
function ros_test_preprocess_ros1__variant1(&$variables, $hook) {
  $variables['text'] .= __FUNCTION__ . ',';
}

/**
 * Implements hook_preprocess_hook().
 */
function ros_test_preprocess_ros2(&$variables, $hook) {
  $variables['text'] .= __FUNCTION__ . ',';
}

/**
 * Implements hook_preprocess_hook().
 */
function ros_test_preprocess_ros2__variant1(&$variables, $hook) {
  $variables['text'] .= __FUNCTION__ . ',';
}
