<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_theme().
 */
function ros_test_theme() {
  return array(
    'ros0' => array(
      'variables' => array(
        'callbacks' => array(),
      ),
      'template' => 'ros0',
    ),
    'ros1' => array(
      'variables' => array(
        'callbacks' => array(),
      ),
      'template' => 'ros1',
    ),
    'ros2' => array(
      'variables' => array(
        'callbacks' => array(),
      ),
      'template' => 'ros2',
    ),
    'ros3' => array(
      'variables' => array(
        'callbacks' => array(),
      ),
      // This one has a theme function.
    ),
  );
}

/**
 * Default theme implementation for theme('ros3').
 *
 * @param array $variables
 *
 * @return string
 */
function theme_ros3(array $variables) {
  $variables['callbacks'][] = __FUNCTION__;
  return implode("\n", $variables['callbacks']);
}

/**
 * Implements hook_theme_registry_alter().
 *
 * @param array $theme_registry
 */
function ros_test_theme_registry_alter(array &$theme_registry) {
  if (isset($theme_registry['ros2'])) {
    // Make sure that the key is set.
    $theme_registry['ros2'] += array('preprocess functions' => array());

    // Remove a preprocess function.
    foreach (array_keys($theme_registry['ros2']['preprocess functions'], 'system_preprocess_ros2') as $i) {
      unset($theme_registry['ros2']['preprocess functions'][$i]);
    }

    // Prepend a preprocess function.
    array_unshift($theme_registry['ros2']['preprocess functions'], '_ros_test_preprocess_ros2_custom_prepend');

    // Append a preprocess function.
    $theme_registry['ros2']['preprocess functions'][] = '_ros_test_preprocess_ros2_custom_append';

    // Append another preprocess function.
    // This one does not match the pattern "*_preprocess_HOOK".
    $theme_registry['ros2']['preprocess functions'][] = '_ros_test_phase0_ro_s2_custom_append';

    // Normalize array keys.
    $theme_registry['ros2']['preprocess functions'] = array_values($theme_registry['ros2']['preprocess functions']);
  }

  if (isset($theme_registry['ros3'])) {
    // Append a preprocess function.
    // This one does not match the pattern "*_preprocess_HOOK".
    $theme_registry['ros3']['preprocess functions'][] = '_ros_test_phase0_ro_s3_custom_append';
  }
}

/**
 * This callback is removed in ros_test_theme_registry_alter().
 *
 * @param array $variables
 * @param string $hook
 */
function system_preprocess_ros2(array &$variables, $hook) {
  $variables['callbacks'][] = __FUNCTION__;
}

/**
 * This callback is prepended in ros_test_theme_registry_alter()
 *
 * @param array $variables
 * @param string $hook
 */
function _ros_test_preprocess_ros2_custom_prepend(array &$variables, $hook) {
  $variables['callbacks'][] = __FUNCTION__;
}

/**
 * This callback is appended in ros_test_theme_registry_alter()
 *
 * @param array $variables
 * @param string $hook
 */
function _ros_test_preprocess_ros2_custom_append(array &$variables, $hook) {
  $variables['callbacks'][] = __FUNCTION__;
}

/**
 * This callback is appended in ros_test_theme_registry_alter()
 *
 * Unlike the previous one, its function name does not match 'preprocess_HOOK'.
 *
 * @param array $variables
 * @param string $hook
 */
function _ros_test_phase0_ro_s2_custom_append(array &$variables, $hook) {
  $variables['callbacks'][] = __FUNCTION__;
}

/**
 * This callback is appended in ros_test_theme_registry_alter()
 *
 * @param array $variables
 * @param string $hook
 */
function _ros_test_phase0_ro_s3_custom_append(array &$variables, $hook) {
  $variables['callbacks'][] = __FUNCTION__;
}

/**
 * Implements hook_preprocess_hook().
 */
function ros_test_preprocess_ros0(&$variables, $hook) {
  $variables['callbacks'][] = __FUNCTION__;
}

/**
 * Implements hook_preprocess_hook().
 */
function ros_test_preprocess_ros1(&$variables, $hook) {
  $variables['callbacks'][] = __FUNCTION__;
}

/**
 * Implements hook_preprocess_hook().
 */
function ros_test_preprocess_ros1__variant1(&$variables, $hook) {
  $variables['callbacks'][] = __FUNCTION__;
}

/**
 * Implements hook_preprocess_hook().
 */
function ros_test_preprocess_ros2(&$variables, $hook) {
  $variables['callbacks'][] = __FUNCTION__;
}

/**
 * Implements hook_preprocess_hook().
 */
function ros_test_preprocess_ros2__variant1(&$variables, $hook) {
  $variables['callbacks'][] = __FUNCTION__;
}

/**
 * Implements hook_process_hook().
 */
function ros_test_process_ros0(&$variables, $hook) {
  $variables['callbacks'][] = __FUNCTION__;
}

/**
 * Implements hook_process_hook().
 */
function ros_test_process_ros1(&$variables, $hook) {
  $variables['callbacks'][] = __FUNCTION__;
}

/**
 * Implements hook_process_hook().
 */
function ros_test_process_ros1__variant1(&$variables, $hook) {
  $variables['callbacks'][] = __FUNCTION__;
}

/**
 * Implements hook_process_hook().
 */
function ros_test_process_ros2(&$variables, $hook) {
  $variables['callbacks'][] = __FUNCTION__;
}

/**
 * Implements hook_process_hook().
 */
function ros_test_process_ros2__variant1(&$variables, $hook) {
  $variables['callbacks'][] = __FUNCTION__;
}

/**
 * Implements hook_process_hook().
 */
function ros_test_process_ros2__variant2(&$variables, $hook) {
  $variables['callbacks'][] = __FUNCTION__;
}
